// ─── EVENTS DATA ─────────────────────────────────────────────────────────────
// Edit this file to add, remove or update events.
//
// Each event must have:
//   id          – unique number
//   title       – event name
//   date        – "YYYY-MM-DD"
//   time        – display string e.g. "6:00 PM"
//   location    – full venue + city
//   category    – must match one of: Music | Art | Food | Tech | Sports | Culture | Wellness | Film
//   description – longer text shown in the detail modal
//   contact     – email address
//   links       – object with optional keys: website, instagram  (full URLs)
//   image       – filename of the poster image (place it in the same folder as index.html)
//               – must be 3:4 portrait ratio; shown as cover fill
//               – if the file is missing the icon emoji is shown as fallback
//   icon        – emoji fallback shown when image is unavailable
// ─────────────────────────────────────────────────────────────────────────────

const EVENTS = [
  {
    id: 1,
    title: 'Bloom Garden Jazz Festival',
    date: '2025-04-05',
    time: '6:00 PM',
    location: 'Cubbon Park Amphitheatre, Bangalore',
    category: 'Music',
    description: 'An enchanting evening of jazz under the stars, featuring 12 local and international jazz ensembles. Bring a blanket and enjoy gourmet food stalls, craft cocktails, and the magic of live music.',
    contact: 'hello@bloomjazz.in',
    links: { website: 'https://example.com', instagram: 'https://instagram.com' },
    image: 'Image1.png',
    icon: '🎷',
  },
  {
    id: 2,
    title: 'Pastel Palette: Watercolor Exhibition',
    date: '2025-04-07',
    time: '11:00 AM',
    location: 'Gallery 88, Indiranagar, Bangalore',
    category: 'Art',
    description: 'A curated showcase of 40 artists exploring the soft, dreamlike world of watercolor. Works span from impressionist landscapes to abstract botanical studies.',
    contact: 'gallery88@art.in',
    links: { website: 'https://example.com' },
    image: 'event-02.jpg',
    icon: '🎨',
  },
  {
    id: 3,
    title: 'Street Eats Food Crawl',
    date: '2025-04-08',
    time: '4:00 PM',
    location: 'Church Street, Bangalore',
    category: 'Food',
    description: 'Join 200+ food enthusiasts on a guided walk through the best street food spots in the city. Includes tastings at 8 curated stops.',
    contact: 'streeteatsbng@gmail.com',
    links: { website: 'https://example.com', instagram: 'https://instagram.com' },
    image: 'event-03.jpg',
    icon: '🍜',
  },
  {
    id: 4,
    title: 'Bengaluru Tech Summit 2025',
    date: '2025-04-10',
    time: '9:00 AM',
    location: 'NIMHANS Convention Centre, Bangalore',
    category: 'Tech',
    description: 'Three days of thought leadership, workshops, and networking for the tech community. Speakers from Google, Anthropic, and leading Indian startups.',
    contact: 'contact@btechsummit.in',
    links: { website: 'https://example.com', instagram: 'https://instagram.com' },
    image: 'event-04.jpg',
    icon: '💻',
  },
  {
    id: 5,
    title: 'Sunrise Yoga at Lal Bagh',
    date: '2025-04-12',
    time: '6:30 AM',
    location: 'Lal Bagh Botanical Garden, Bangalore',
    category: 'Wellness',
    description: 'Begin your weekend with a mindful yoga session among 200-year-old trees. All levels welcome. Mats provided.',
    contact: 'yogalalbagh@gmail.com',
    links: { instagram: 'https://instagram.com' },
    image: 'event-05.jpg',
    icon: '🧘',
  },
  {
    id: 6,
    title: 'Open Mic Night: Stories Untold',
    date: '2025-04-12',
    time: '7:30 PM',
    location: 'Stoa, Koramangala, Bangalore',
    category: 'Culture',
    description: 'An intimate open mic where poets, storytellers, and spoken word artists take the stage. Sign up at the door!',
    contact: 'stoa.events@gmail.com',
    links: { instagram: 'https://instagram.com' },
    image: 'event-06.jpg',
    icon: '🎙️',
  },
  {
    id: 7,
    title: 'Indie Film Screening: Whispers',
    date: '2025-04-14',
    time: '8:00 PM',
    location: 'PVR Cinemas, Orion Mall, Bangalore',
    category: 'Film',
    description: 'World premiere of the acclaimed short film anthology "Whispers" — seven short films by emerging South Indian directors exploring memory, loss, and belonging.',
    contact: 'indiefilm@studiocraft.in',
    links: { website: 'https://example.com' },
    image: 'event-07.jpg',
    icon: '🎬',
  },
  {
    id: 8,
    title: 'Monsoon Half Marathon',
    date: '2025-04-15',
    time: '5:30 AM',
    location: 'UB City, Bangalore',
    category: 'Sports',
    description: "The city's most beloved running event returns! Choose from 5K, 10K, and 21K routes through the heart of Bangalore.",
    contact: 'run@marathonbng.com',
    links: { website: 'https://example.com', instagram: 'https://instagram.com' },
    image: 'event-08.jpg',
    icon: '🏃',
  },
  {
    id: 9,
    title: 'Synth & Vinyl Night',
    date: '2025-04-18',
    time: '9:00 PM',
    location: 'Fandom, Indiranagar, Bangalore',
    category: 'Music',
    description: 'Deep dives into analog synthesis and vinyl records. Two resident DJs and two guest artists bring 4 hours of uninterrupted electronic bliss.',
    contact: 'fandom.bng@gmail.com',
    links: { instagram: 'https://instagram.com' },
    image: 'event-09.jpg',
    icon: '🎹',
  },
  {
    id: 10,
    title: 'Ceramic Arts Workshop',
    date: '2025-04-19',
    time: '2:00 PM',
    location: 'The Pottery House, HSR Layout, Bangalore',
    category: 'Art',
    description: 'Learn hand-building and wheel-throwing techniques in this beginner-friendly 3-hour workshop. All materials provided. Take home your creation!',
    contact: 'potteryhouse@craft.in',
    links: { website: 'https://example.com', instagram: 'https://instagram.com' },
    image: 'event-10.jpg',
    icon: '🏺',
  },
  {
    id: 11,
    title: 'Plant-Based Brunch Fest',
    date: '2025-04-20',
    time: '10:00 AM',
    location: 'Social, Koramangala, Bangalore',
    category: 'Food',
    description: 'Celebrating the best of vegan and plant-forward cuisine from 25 chefs and restaurants. Live cooking demos, workshops, and tastings all day.',
    contact: 'plantfest@foodlove.in',
    links: { website: 'https://example.com' },
    image: 'event-11.jpg',
    icon: '🥗',
  },
  {
    id: 12,
    title: 'Cloud & AI Conference',
    date: '2025-04-22',
    time: '10:00 AM',
    location: 'IISc Campus, Bangalore',
    category: 'Tech',
    description: "India's premier AI research conference with keynotes, panels, and paper presentations. Topics include LLMs, computer vision, and responsible AI.",
    contact: 'ai@iisc.ac.in',
    links: { website: 'https://example.com' },
    image: 'event-12.jpg',
    icon: '🤖',
  },
  {
    id: 13,
    title: 'Kathak Recital: Monsoon Ragas',
    date: '2025-04-23',
    time: '7:00 PM',
    location: 'Chowdiah Memorial Hall, Bangalore',
    category: 'Culture',
    description: 'Renowned Kathak artist Priya Malhotra presents a full-length solo recital celebrating the monsoon season through classical dance.',
    contact: 'tickets@chowdiah.in',
    links: { website: 'https://example.com' },
    image: 'event-13.jpg',
    icon: '💃',
  },
  {
    id: 14,
    title: 'Meditation & Sound Bath',
    date: '2025-04-26',
    time: '8:00 AM',
    location: 'Nandi Hills, Bangalore',
    category: 'Wellness',
    description: 'A two-hour immersive sound healing session using crystal bowls, gongs, and chimes in the serene surroundings of Nandi Hills. Limited to 30 participants.',
    contact: 'heal@soundsanctuary.in',
    links: { instagram: 'https://instagram.com' },
    image: 'event-14.jpg',
    icon: '🔔',
  },
  {
    id: 15,
    title: 'IPL Watch Party',
    date: '2025-04-28',
    time: '7:00 PM',
    location: 'Hard Rock Cafe, Brigade Road, Bangalore',
    category: 'Sports',
    description: 'Watch live IPL cricket action on the big screen with fellow fans. Drink specials and food bundles all night!',
    contact: 'events@hardrock.in',
    links: { website: 'https://example.com' },
    image: 'event-15.jpg',
    icon: '🏏',
  },
  {
    id: 16,
    title: "Children's Book Fair",
    date: '2025-04-05',
    time: '10:00 AM',
    location: 'Bangalore International Exhibition Centre',
    category: 'Culture',
    description: 'Three days of storytelling, author meets, puppet shows, and thousands of books for young readers. Free entry for kids under 12.',
    contact: 'bookfair@culture.in',
    links: { website: 'https://example.com' },
    image: 'event-16.jpg',
    icon: '📚',
  },
  {
    id: 17,
    title: 'Photography Walk: Old Bangalore',
    date: '2025-04-10',
    time: '7:00 AM',
    location: 'Pete Area, Bangalore',
    category: 'Art',
    description: 'Explore the narrow lanes and heritage architecture of Old Bangalore with a professional photographer guide. Bring your camera!',
    contact: 'photowalk@lensart.in',
    links: { instagram: 'https://instagram.com' },
    image: 'event-17.jpg',
    icon: '📷',
  },
  {
    id: 18,
    title: 'Rooftop Cinema Night',
    date: '2025-04-19',
    time: '7:30 PM',
    location: '1 MG Road Rooftop, Bangalore',
    category: 'Film',
    description: "Classic cinema under the stars. Tonight: screening of Mani Ratnam's timeless Bombay, with pre-show cocktails and live music.",
    contact: 'rooftopcinema@events.in',
    links: { website: 'https://example.com', instagram: 'https://instagram.com' },
    image: 'event-18.jpg',
    icon: '🎞️',
  },
];
